# promptToReturnFromSubprocess: false

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --syntax-theme="Dracula"
    # pager: diff-so-fancy
  commitPrefix:
    pattern: "^(\\w+-\\w+).*"
    replace: '$1 - '

services:
  'git@gitlab.inplatlabs.ru': 'gitlab:git@gitlab.inplatlabs.ru'
